In [9]:
'''find the shape, size and dimension 
[[1,2,3,4],
 [5,6,7,8],
 [9,10,11,12]]
'''

import numpy as np 
arr=np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr.shape)
print (arr.size)
print (arr.ndim)

(3, 4)
12
2


In [10]:
'''access the first row 
[[1,2,3,4]]
 [5,6,7,8],
 [9,10,11,12]]
'''

arr=np.array ([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print (arr[0])

[1 2 3 4]


In [12]:
'''How do you access the element at the third row and fourth column from the given numpy array 
   [[1,2,3,4],[5,6,7,8],[9,10,11,12]]  
'''

print (arr[2][3])

12


In [13]:
'''odd index element 
'''

odd_index_element = arr [::2, 1::2]  
print (odd_index_element)

[[ 2  4]
 [10 12]]


In [14]:
'''genrate random 3*3 matrix with value 0 and 1 
'''

arr = np.random.randint(0, 2, size=(3, 3))
print("Random 3x3 matrix with values 0 and 1:")
print(arr)

Random 3x3 matrix with values 0 and 1:
[[0 0 1]
 [0 1 0]
 [0 0 0]]


In [ ]:
'''diffrence between np.random.rand and np.random.randn
'''

uniform_array = np.random.rand(2, 3)
print("Uniform Distribution Array:")
print(uniform_array)

In [21]:
'''how to increase the dimension of the following array  
'''
import numpy as np
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print("Original array:")
print(arr)

reshaped_arr = arr.reshape((1, 3, 4))
print("\nArray with increased dimensions:")
print(reshaped_arr)
print("Shape of the reshaped array:", reshaped_arr.shape)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Array with increased dimensions:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
Shape of the reshaped array: (1, 3, 4)


In [23]:
'''how to transpose 
'''


import numpy as np
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

print("Original array:")
print(arr)
print("Transposed array:")
transposed_arr = arr.T
print(transposed_arr)


Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Transposed array:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [25]:
'''Consider the following matrix 
matrix A [[1,2,3,4] [5,6,7,8] [9,10,11,12]]
matrix B [[1,2,3,4] [5,6,7,8] [9,10,11,12]]
'''


import numpy as np
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

index_wise_multiplication = a * b
print("Index-wise Multiplication:\n", index_wise_multiplication)


matrix_multiplication = np.dot(a, b.T) 
print("\nMatrix Multiplication:\n", matrix_multiplication)


addition = a + b
print("\nAddition of matrices:\n", addition)

subtraction = a - b
print("\nSubtraction of b from a:\n", subtraction)

division = a / b
print("\nDivision of a by b:\n", division)



Index-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]

Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]

Addition of matrices:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]

Subtraction of b from a:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

Division of a by b:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [26]:
'''Numpy can be used to swap the byte order of an array 
'''


import numpy as np

arr = np.array([1, 256, 1024], dtype=np.int32)

print("Original array:")
print(arr)
print("Data type:", arr.dtype)


swapped_arr = arr.byteswap().newbyteorder()

print("\nSwapped byte order array:")
print(swapped_arr)
print("Data type:", swapped_arr.dtype)



Original array:
[   1  256 1024]
Data type: int32

Swapped byte order array:
[   1  256 1024]
Data type: >i4


In [27]:
'''what is the signifiacnce of the np.linalg.inv function 
'''

import numpy as np


A = np.array([[1, 2], [3, 4]])

A_inv = np.linalg.inv(A)

print("Matrix A:")
print(A)

print("\nInverse of matrix A:")
print(A_inv)


I = np.dot(A, A_inv)

print("\nProduct of A and its inverse (should be identity matrix):")
print(I)




Matrix A:
[[1 2]
 [3 4]]

Inverse of matrix A:
[[-2.   1. ]
 [ 1.5 -0.5]]

Product of A and its inverse (should be identity matrix):
[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]
